### ISSUE TITLE
New Task Feature

### ISSUE THREAD

**Issue by rawkakani** [rawkakani/swiftloop#2]
Here we will enable the team lead to be able to create a task
which can be seen in the figma file [here](https://www.figma.com/file/qmFPAXZ4EnNZMdyIjr3WhD/MVP?type=design&node-id=342-4302&mode=design&t=zdnRNwl4xRFnrwpl-4)

This would ideally be under the dashboard route and would have a dependency with creating a quick standup as the button to create quick stand up is by the dasboard

Requirements

- Task Name
- Date Time
- Priority
- Assigned To

Task Modal - Firestore Document

```
{
id : // firestore document id 
name: string
createdDate: dateTime
dueDate: dateTime
assignedTo: string // team member id
status: string // enums of BACKLOG, TODO, INPROGRESS, DONE
}
```

Team modal - Firestore Document (update)[https://github.com/rawkakani/swiftloop/issues/6]

```
{
// current modal
tasks: array<tasks> // array of firestore document id for tasks
}
```

you can pull the team members to populate the team id from the team firestore document that shall look like [this](https://github.com/rawkakani/swiftloop/issues/6)

**Comment by KitwanaSh** [comment]
I am still unable to send the data when i click save in the "Add task form". I'm gonna need some help from any Firebase master.
